#!/bin/bash

#
# PATH
# set PATH to point to jeriko's folder first
#
export PATH=`dirname $0`:$PATH

#
# RUN IN BATCH
# environment variables specific to run-in-batch
#
RUN_IN_BATCH_MAX_PROCESSES=10

#
# RUN IN PARALLEL
# environment variables specific to run-in-parallel
#
RUN_IN_PARALLEL_MAX_PROCESSES=10
RUN_IN_PARALLEL_MAX_WAIT=10

#
# SCAN WHOIS
# environment vriables specific to scan-whois
#
WHOIS_SERVERS="whois.apnic.net whois.arin.net whois.ripe.net whois.networksolutions.com"

#
# NMAP
# configure nmap
#
NMAP_TCP_SCAN_METHOD="-sS -P0"
NMAP_UDP_SCAN_METHOD="-sU -P0"

#
# NESSUS
# configure nessus
#
NESSUS_HOST=127.0.0.1
NESSUS_PORT=1241
NESSUS_USER=user
NESSUS_PASS=pass

#
# WGET
# configure wget
#
WGET_URL_SCAN_METHOD="-l1"
WGET_URL_STREAM_METHOD=

#
# LOAD USER DEFINED
# load jeriko profile from the user's folder
#
if [ -f ~/.jerikorc ]
then
	. ~/.jerikorc
fi

#
# LOAD SESSION SPECIFIC
# load jeriko profile from the current folder
#
if [ -f ./.jerikorc ]
then
	. ./.jerikorc
fi

#
# CHECK DEPENDENCIES
#
JERIKO_ENVIRONMENTLESS=true . environment-check

#
# KILL ALL
# kill all child processes when CTRL+C
#
KILL_ALL() { pkill -P $$; exit; }

trap KILL_ALL INT
