#!/bin/sh
. `dirname $0`/environment-load

if [ "$ARGS" ]
then
	for TARGET in $ARGS
	do
		echo $TARGET
	done
else
	cat
fi | sort | uniq | while read TARGET
do
	for USER in $EXPAND_URL_CREDENTIALS
	do
		for PASS in $EXPAND_URL_CREDENTIALS
		do
			echo $TARGET | sed -r -e "s/:\/\//:\/\/$USER:@/"
			echo $TARGET | sed -r -e "s/:\/\//:\/\/:$PASS@/"
			echo $TARGET | sed -r -e "s/:\/\//:\/\/$USER:$PASS@/"
		done
	done
done
