#!/bin/sh
if [ -f `dirname $0`/environment-load ]; then . `dirname $0`/environment-load; fi

((cat *.nbe 2>/dev/null | extract-services-nbe) & (cat *.gnmap 2>/dev/null | extract-services-gnmap)) | sort | uniq
