#!/bin/sh
if [ -f targets.txt ]; then cat targets.txt | while read TARGET; do cat << EOF
fast-tcp-scan $TARGET
fast-udp-scan $TARGET
full-tcp-scan $TARGET
full-udp-scan $TARGET
vulnerability-scan $TARGET
EOF
done; fi
