#!/bin/sh
. `dirname $0`/environment-load
extract-services | grep -E 'http|https' | awk -F, '{ print $4"://"$1":"$2"/" }' | sed -r -e 's/^.*https:/https:/' -e 's/^.*http:/http:/' -e 's/^https-[^:]*/https/' -e 's/http-[^:]*/http/' | sort | uniq
