#!/bin/sh
if [ -f targets.txt ]
then
	cat targets.txt | while read TARGET
	do
cat << EOF
scan-ports-tcp-fast $TARGET
scan-ports-udp-fast $TARGET
scan-ports-tcp-full $TARGET
scan-ports-udp-full $TARGET
scan-vulnerabilities $TARGET
EOF
	done
fi
