#!/bin/sh
if [ -f `dirname $0`/environment-load ]; then . `dirname $0`/environment-load; fi

generate-ip-batch | while read TARGET
do
cat << EOF
scan-ports-tcp-fast $TARGET
scan-ports-udp-fast $TARGET
scan-ports-tcp-full $TARGET
scan-ports-udp-full $TARGET
scan-vulnerabilities $TARGET
EOF
done
