#!/bin/bash

#
# PATH
# set PATH to point to jeriko's folder first
#
export PATH=`dirname $0`:$PATH

#
# KILL ALL
# kill all child processes when CTRL+C
#
KILL_ALL() { pkill -P $$; exit; }

trap KILL_ALL INT

#
# RUN IN BATCH
# environment variables specific to run-in-batch
#
RUN_IN_BATCH_MAX_PROCESSES=10

#
# RUN IN PARALLEL
# environment variables specific to run-in-parallel
#
RUN_IN_PARALLEL_MAX_PROCESSES=10
RUN_IN_PARALLEL_MAX_WAIT=10

#
# PGREP
# configure pgrep
# 
if [ ! -x `which pgrep` ]
then
	echo '[x] cannot find pgrep' 1>&2
	exit
fi

#
# PKILL
# configure pkill
# 
if [ ! -x `which pgrep` ]
then
	echo '[x] cannot find pkill' 1>&2
	exit
fi

#
# EXPR
# configure expr
# 
if [ ! -x `which expr` ]
then
	echo '[x] cannot find expr' 1>&2
	exit
fi


#
# NMAP
# configure nmap
#
if [ ! -x `which nmap` ]
then
	echo '[x] cannot find nmap' 1>&2
	exit
fi

NMAP_TCP_SCAN_METHOD="-sS -P0"
NMAP_UDP_SCAN_METHOD="-sU -P0"

#
# NESSUS
# configure nessus
#
if [ ! -x `which nessus` ]
then
	echo '[x] cannot find nessus' 1>&2
	exit
fi

NESSUS_HOST=127.0.0.1
NESSUS_PORT=1241
NESSUS_USER=user
NESSUS_PASS=pass

#
# LOAD USER DEFINED
# load jeriko profile from the user's folder
#
if [ -f ~/.jerikorc ]
then
	. ~/.jerikorc
fi

#
# LOAD SESSION SPECIFIC
# load jeriko profile from the current folder
#
if [ -f ./.jerikorc ]
then
	. ./.jerikorc
fi

#
# JERIKO STRICT CHECKS
#
if [ "$JERIKO_STRICT_CHECKS" ]
then
	#
	# NESSUSD
	# detect if nessusd is running
	#
	if [ "$NESSUS_HOST" = "127.0.0.1" -o "$NESSUS_HOST" = "localhost" ]
	then
		if [ ! `pgrep '^nessusd$'` ]
		then
			echo '[x] cannot find nessusd' 1>&2
			exit
		fi
	fi
fi
