#!/bin/sh
. `dirname $0`/environment-load

if [ ! $RUN_IN_PARALLEL_MAX_PROCESSES ]; then RUN_IN_PARALLEL_MAX_PROCESSES=10; fi
if [ ! $RUN_IN_PARALLEL_MAX_WAIT ]; then RUN_IN_PARALLEL_MAX_WAIT=10; fi
if [ $1 ]; then RUN_IN_PARALLEL_MAX_PROCESSES=$1; fi
if [ $2 ]; then RUN_IN_PARALLEL_MAX_WAIT=$2; fi

CUR_PROCESS=0

while true
do
	if [ `pgrep -P $$ | wc -l` -lt $RUN_IN_PARALLEL_MAX_PROCESSES ]
	then
		read PROCESS

		if [ ! "$PROCESS" ]
		then
			break
		fi

		echo "[p:0000] executing: $PROCESS"

		CUR_PROCESS=`expr $CUR_PROCESS + 1`

		($PROCESS 2>&1 | while read LINE; do echo "[p:`printf "%.4d" $CUR_PROCESS`] $LINE"; done) &

		echo "[p:0000] pid: $!"
	else
		echo "[p:0000] currently running pids:" `pgrep -P $$ | sed -r -e 's/\n/ /g'`
		echo "[p:0000] sleeping: $RUN_IN_PARALLEL_MAX_WAIT"
		sleep $RUN_IN_PARALLEL_MAX_WAIT
	fi
done

echo "[p:0000] finishing up:" `pgrep -P $$ | sed -r -e 's/\n/ /g'`
wait
