#!/bin/sh
. `dirname $0`/environment-load

TIMESTAMP=`date +%s`
ARGS=$@

if [ "$ARGS" ]
then
	for TARGET in $ARGS
	do
		echo $TARGET
	done
else
	cat
fi | sort | uniq | while read TARGET
do
	nmap -vvv $NMAP_UDP_SCAN_METHOD -p1-65535 -oA "full_udp_scan_$TARGET_$TIMESTAMP" $TARGET
done
