#!/bin/sh
. `dirname $0`/environment-load

TIMESTAMP=`date +%s`
METASPLOIT_RESOURCE_FILE="autopwn_${TIMESTAMP}.rc"

generate-exploit-batch > $METASPLOIT_RESOURCE_FILE
msfconsole -r $METASPLOIT_RESOURCE_FILE
