#!/bin/sh
. `dirname $0`/environment-load

if [ `which apt-get` ]
then
	auto_install_package() {
		sudo apt-get install $@
	}
elif [ `which yum` ]
then
	auto_install_package() {
		sudo yum install $@
	}
fi

install_if_not_present() {
	if [ ! `which $1` ]
	then
		if [ "$2" ]
		then
			auto_install_package $2
		else
			auto_install_package $1
		fi
	fi
}

install_if_not_present firefox
install_if_not_present Xvfb xvfb
install_if_not_present import imagemagic
install_if_not_present nmap
install_if_not_present nessus
install_if_not_present msfconsole metasploit
