#!/bin/bash

if [ ! "$JERIKO_ENVIRONMENTLESS" ]
then
	if [ -f `dirname $0`/environment-load ]; then . `dirname $0`/environment-load; fi
	JERIKO_STRICT_CHECKS=true
fi

check_for_cmd() {
	if [ ! `which $1` ]
	then
		echo "cannot find $1" 1>&2
		exit
	fi
}

check_for_process() {
	if [ ! `pgrep "^${1}$"` ]
	then
		echo "$1 is not running" 1>&2
		exit
	fi
}

if [ ! "$JERIKO_CHECKLESS" ]
then
	#
	# BASIC CHECKS
	#
	check_for_cmd expr
	check_for_cmd pgrep
	check_for_cmd pkill
	check_for_cmd screen
	check_for_cmd script
	check_for_cmd wget
	check_for_cmd nmap
	check_for_cmd msfconsole
	check_for_cmd nessus

	#
	# JERIKO STRICT CHECKS
	#
	if [ "$JERIKO_STRICT_CHECKS" ]
	then
		if [ "$NESSUS_HOST" = "127.0.0.1" -o "$NESSUS_HOST" = "localhost" ]
		then
			check_for_process nessusd
		fi
	fi
fi
