#!/bin/sh
. `dirname $0`/load-environment

if [ ! $RUN_IN_PARALLEL_MAX_PROCESSES ]
then
	RUN_IN_PARALLEL_MAX_PROCESSES=10
fi

if [ $1 ]
then
	RUN_IN_PARALLEL_MAX_PROCESSES=$1
fi

CUR_PROCESS=0
TMP_PROCESS=`mktemp`

echo "[p:0000] tempfile: $TMP_PROCESS"

while true
do
	if [ `cat $TMP_PROCESS | wc -l` -lt $RUN_IN_PARALLEL_MAX_PROCESSES ]
	then
		read PROCESS

		if [ ! "$PROCESS" ]
		then
			break
		fi

		echo "[p:0000] execting: $PROCESS"

		CUR_PROCESS=`expr $CUR_PROCESS + 1`
		echo $CUR_PROCESS >> $TMP_PROCESS

		($PROCESS 2>&1 | while read LINE; do echo "[p:`printf "%.4d" $CUR_PROCESS`] $LINE"; done; cat $TMP_PROCESS | grep -vE "^$CUR_PROCESS$" | tee $TMP_PROCESS 1>/dev/null) &
	else
		echo "[p:0000] prunning:" `cat $TMP_PROCESS | sed -r -e 's/\n/ /g'`
		echo "[p:0000] sleeping: 10"
		sleep 10
	fi
done
wait

rm $TMP_PROCESS
