#!/bin/sh
. `dirname $0`/environment-load

generate-ip-batch | while read TARGET
do
cat << EOF
scan-ports-tcp-fast $TARGET
scan-ports-udp-fast $TARGET
scan-ports-tcp-full $TARGET
scan-ports-udp-full $TARGET
scan-vulnerabilities $TARGET
EOF
done
