#!/bin/sh
#
# PATH
#
export PATH=`dirname $0`:$PATH

#
# RUN IN PARALLEL
#
RUN_IN_PARALLEL_MAX_PROCESSES=10

#
# NMAP
#
if [ ! -x `which nmap` ]
then
	echo '[x] cannot find nmap' 1>&2
	exit 1
fi

NMAP_TCP_SCAN_METHOD="-sS -P0"
NMAP_UDP_SCAN_METHOD="-sU -P0"

#
# NESSUS
#
if [ ! -x `which nessus` ]
then
	echo '[x] cannot find nessus' 1>&2
	exit 1
fi

NESSUS_HOST=127.0.0.1
NESSUS_PORT=1241
NESSUS_USER=user
NESSUS_PASS=pass

#
# LOAD USER DEFINED
#
if [ -f ~/.jerikorc ]
then
	. ~/.jerikorc
fi

#
# LOAD SESSION SPECIFIC
#
if [ -f ./.jerikorc ]
then
	. ./.jerikorc
fi
