#!/bin/sh
if [ -f `dirname $0`/environment-load ]; then . `dirname $0`/environment-load; fi

TIMESTAMP=`date +%s`

if [ "$@" ]
then
	for TARGET in $@
	do
		echo $TARGET
	done
else
	cat
fi | sort | uniq | while read TARGET
do
	FRIENDLYNAME=`echo $TARGET | sed -r -e 's/\W/_/g' -e 's/_+/_/g'`
	wget --progress=dot -P url_scan_${FRIENDLYNAME}_$TIMESTAMP --protocol-directories -x --save-headers $WGET_URL_SCAN_METHOD $TARGET 2>&1 | tee url_scan_${FRIENDLYNAME}_$TIMESTAMP.log
done
