#!/bin/sh
. `dirname $0`/environment-load

TIMESTAMP=`date +%s`
ARGS=$@

if [ "$ARGS" ]
then
	for TARGET in $ARGS
	do
		echo $TARGET
	done
else
	cat
fi | sort | uniq | while read QUERY
do
	FRIENDLYQUERY=`echo $QUERY | sed -r -e 's/\W/_/g' -e 's/_+/_/g'`

	whois $QUERY | tee whois_${FRIENDLYQUERY}_$TIMESTAMP

	for SERVER in $WHOIS_SERVERS
	do
		FRIENDLYSERVER=`echo $SERVER | sed -r -e 's/\W/_/g' -e 's/_+/_/g'`
		whois -h $SERVER $QUERY | tee whois_${FRIENDLYQUERY}_${FRIENDLYSERVER}_$TIMESTAMP
	done
done
