#!/bin/sh
if [ -f `dirname $0`/environment-load ]; then . `dirname $0`/environment-load; fi

TIMESTAMP=`date +%s`
COMMAND=$@

if [ ! "$COMMAND" ]
then
	COMMAND="bash"
fi

screen -S jeriko.$TIMESTAMP script -c "$COMMAND" jeriko_$TIMESTAMP.session
