#!/bin/sh
. `dirname $0`/environment-load

TIMESTAMP=`date +%s`
COMMAND=$@

if [ ! "$COMMAND" ]
then
	COMMAND="bash"
fi

screen -d -m -S jeriko.$TIMESTAMP script -c "$COMMAND" jeriko_$TIMESTAMP.session
